// AUTO-GENERATED by scripts/gen-constraints.mjs from vendor/openapi/keeper.yaml — do not edit by hand.
// Re-run: npm run gen:api
export const CONSTRAINTS = {
  cadenceIntervalSecondsMin: 30,
} as const;
