// Typed wrappers over the Keeper Operator API. Matches vendor/openapi/keeper.yaml.
//
// Types are imported from ./types.gen.ts (generated by `npm run gen:api`).
// Manual fallback interfaces (SoulprintFacts, ErrandAccepted) were removed after
// the final regen on the full huma OpenAPI spec (all schemas now live in components).

import { apiGet, apiSend, ApiError } from './client';
import { tokenStore } from './tokenStore';
import type { components } from './types.gen';

// --- Re-export from generated openapi (source of truth) ---

export type IncarnationStatus = components['schemas']['IncarnationStatus'];
export type SoulTransport = components['schemas']['SoulTransport'];
export type SoulStatus = components['schemas']['SoulStatus'];

// IncarnationGetReply — single incarnation projection (used in both list and get).
// The old name IncarnationSummary is kept as an alias for backward compatibility.
export type IncarnationGetReply = components['schemas']['IncarnationGetReply'];
export type IncarnationSummary = IncarnationGetReply;
export type IncarnationListReply = components['schemas']['IncarnationListReply'];
export type StateHistoryEntry = components['schemas']['StateHistoryEntry'];
export type IncarnationHistoryReply = components['schemas']['IncarnationHistoryReply'];
// Run-view (GET .../runs + .../runs/{apply_id}) — apply_run is NOT Voyage: rollup
// of apply_runs by apply_id for a single incarnation (create/rerun-last/operational scenario run).
export type RunSummaryEntry = components['schemas']['RunSummaryEntry'];
export type IncarnationRunsReply = components['schemas']['IncarnationRunsReply'];
// input — masked snapshot of the operator input for the run (secrets already
// ***MASKED*** on the backend write path). Extended manually until the vendor
// openapi is re-synced and `npm run gen:api` picks the field into the base schema.
export type RunDetailReply = components['schemas']['RunDetailReply'] & {
  input?: Record<string, unknown>;
};
export type RunHostStatusEntry = components['schemas']['RunHostStatusEntry'];

// GET /runs/{apply_id}/tasks (NIM-37 Schema-2). Server joins the plan (name/module/
// params/no_log/passage) with per-host outcomes from audit (task.executed) by plan_index:
// live AND history in one response. Core schemas: RunTaskEntry/RunTaskHostEntry/
// RunTaskErrorEntry/RunTasksReply; aliases keep the old names for consumers.
// output — register_data (a structure, NOT a string); hosts/tasks are nullable per contract.
export type RunTaskHost = components['schemas']['RunTaskHostEntry'];
export type RunTaskError = components['schemas']['RunTaskErrorEntry'];
export type RunTaskView = components['schemas']['RunTaskEntry'];
export type RunTasksReply = components['schemas']['RunTasksReply'];
export type RunStatus = NonNullable<RunSummaryEntry['status']>;
// Global run-view (GET /v1/runs + /v1/runs/stats) — the same apply_runs, but across ALL incarnations.
export type GlobalRunEntry = components['schemas']['GlobalRunEntry'];
export type RunsListReply = components['schemas']['RunsListReply'];
export type RunsStatsBucket = components['schemas']['RunsStatsBucket'];
export type RunsStatsReply = components['schemas']['RunsStatsReply'];
export type IncarnationCreateRequest = components['schemas']['IncarnationCreateRequest'];
export type IncarnationCreateReply = components['schemas']['IncarnationCreateReply'];
export type IncarnationRunRequest = components['schemas']['IncarnationRunRequest'];
export type IncarnationRunReply = components['schemas']['IncarnationRunReply'];
// Tide mode removed (ADR-043 Voyage replaces Tide); IncarnationRunTideReply is not exported.
export type IncarnationRunAnyReply = IncarnationRunReply;
export type IncarnationUnlockRequest = components['schemas']['IncarnationUnlockRequest'];
export type IncarnationUnlockReply = components['schemas']['IncarnationUnlockReply'];
export type IncarnationUpgradeRequest = components['schemas']['IncarnationUpgradeRequest'];
export type IncarnationUpgradeReply = components['schemas']['IncarnationUpgradeReply'];
// upgrade-paths (NIM-34): version-transition preview — found/legacy, direction,
// reachable, applicable state migrations. Read-side of incarnation.upgrade.
export type IncarnationUpgradePathsReply = components['schemas']['IncarnationUpgradePathsReply'];
export type UpgradePathRef = components['schemas']['UpgradePathRef'];
export type UpgradePathTarget = components['schemas']['UpgradePathTarget'];
// StateSchemaMigration is already re-exported below (Schema explorer) — not redeclared here.
export type IncarnationDestroyReply = components['schemas']['IncarnationDestroyReply'];

export type SoulListEntry = components['schemas']['SoulListEntry'];
export type SoulListReply = components['schemas']['SoulListReply'];
export type SoulStatsReply = components['schemas']['SoulStatsReply'];
export type ClusterReply = components['schemas']['ClusterReply'];
export type ClusterInstanceEntry = components['schemas']['ClusterInstanceEntry'];
// typed_facts is now typed directly in the generated SoulprintReadReply schema.
export type SoulprintReadReply = components['schemas']['SoulprintReadReply'];
export type SoulIssueTokenReply = components['schemas']['SoulIssueTokenReply'];
export type SoulCreateRequest = components['schemas']['SoulCreateRequest'];
export type SoulCreateReply = components['schemas']['SoulCreateReply'];
export type SoulCovenAssignRequest = components['schemas']['SoulCovenAssignRequest'];
export type SoulCovenAssignReply = components['schemas']['SoulCovenAssignReply'];
export type SoulCovenAssignSelector = components['schemas']['SoulCovenAssignSelector'];
export type SoulTraitsAssignRequest = components['schemas']['SoulTraitsAssignRequest'];
export type SoulTraitsAssignReply = components['schemas']['SoulTraitsAssignReply'];
export type SoulHistoryReply = components['schemas']['SoulHistoryReply'];
export type SoulHistoryItem = components['schemas']['SoulHistoryItem'];
export type SoulHistoryType = NonNullable<SoulHistoryItem['type']>;
// SoulprintFacts and nested schemas — from generated components (final huma spec).
export type SoulprintNetworkInterface = components['schemas']['SoulprintNetworkInterface'];
export type SoulprintNetworkFacts = components['schemas']['SoulprintNetworkFacts'];
export type SoulprintMemoryFacts = components['schemas']['SoulprintMemoryFacts'];
export type SoulprintCpuFacts = components['schemas']['SoulprintCpuFacts'];
export type SoulprintKernelFacts = components['schemas']['SoulprintKernelFacts'];
export type SoulprintOsFacts = components['schemas']['SoulprintOsFacts'];
export type SoulprintFacts = components['schemas']['SoulprintFacts'];

// Host-vitals (NIM-86/NIM-88): host utilization from Redis — latest + window
// (sparklines, newest-first) + freshness. Aggregate per incarnation without a window.
export type SoulTelemetryReply = components['schemas']['SoulTelemetryReply'];
export type IncarnationTelemetryReply = components['schemas']['IncarnationTelemetryReply'];
export type HostTelemetry = components['schemas']['HostTelemetry'];
export type UtilizationLatest = components['schemas']['UtilizationLatest'];
export type UtilizationWindowPoint = components['schemas']['UtilizationWindowPoint'];
export type TelemetryDisk = components['schemas']['TelemetryDisk'];

// Extension of OperatorCreateRequest: optional `roles[]` — list of role names
// to immediately enroll the new Archon into. The field was added by the backend
// "create-with-roles" slice; until it ships, the server ignores the field (200), or
// responds 404/501 on the extended endpoint — UI degrades to creating without roles.
export type OperatorCreateRequest = components['schemas']['OperatorCreateRequest'] & {
  roles?: string[];
};
export type OperatorCreateReply = components['schemas']['OperatorCreateReply'];
export type OperatorRevokeRequest = components['schemas']['OperatorRevokeRequest'];
export type IssueTokenReply = components['schemas']['IssueTokenReply'];
export type Operator = components['schemas']['Operator'];
export type OperatorListReply = components['schemas']['OperatorListReply'];
export type OperatorAuthMethod = NonNullable<Operator['auth_method']>;
export type OperatorCreatedVia = NonNullable<Operator['created_via']>;

// Provisioning-policy — allowed operator-creation methods (ADR-058 Part B).
// GET/PUT /v1/provisioning-policy. Type from the schema; method enum — from the contract.
export type ProvisioningPolicyReply = components['schemas']['ProvisioningPolicyReply'];
export type ProvisioningPolicyUpdateRequest = components['schemas']['ProvisioningPolicyUpdateRequest'];
// ProvisioningMethod is derived from the generated schema — when a method is added on
// the backend, the gen type updates automatically and this alias picks it up without manual edits.
export type ProvisioningMethod = NonNullable<ProvisioningPolicyUpdateRequest['allowed_methods']>[number];

export type AuditEvent = components['schemas']['AuditEvent'];
export type AuditEventListReply = components['schemas']['AuditEventListReply'];
export type AuditEventSource = NonNullable<AuditEvent['source']>;

export type PushApplyRequest = components['schemas']['PushApplyRequest'];
export type PushApplyReply = components['schemas']['PushApplyReply'];
export type PushApplyView = components['schemas']['PushApplyView'];
export type PushRunListReply = components['schemas']['PushRunListReply'];
export type PushRunListEntry = components['schemas']['PushRunListEntry'];
export type PushSummaryCounts = components['schemas']['PushSummaryCounts'];
export type PushRunStatus = NonNullable<PushRunListEntry['status']>;

// Tide-runs removed from the API (Voyage ADR-043 replaces Tide, ADR-040 W-4 revoked).
// Types are not exported; keeperApi.tides kept as a stub until the pages are cleaned up.

export type ErrandRunRequest = components['schemas']['ErrandRunRequest'];
// ErrandAccepted is now from generated components (final huma spec).
export type ErrandAccepted = components['schemas']['ErrandAccepted'];
export type ErrandResult = components['schemas']['ErrandResult'];
export type ErrandListReply = components['schemas']['ErrandListReply'];
export type ErrandStatus = NonNullable<ErrandResult['status']>;

// Multi-target Errand (ErrandRun) — slice 2026-05-27 W1, openapi not committed yet.
// Narrow local types; backend shape agreed in the delegation spec.
export type ErrandRunStatus = 'pending' | 'running' | 'success' | 'partial_failed' | 'failed' | 'cancelled';
export type ErrandRunOnFailure = 'abort' | 'continue';

export interface ErrandRunTarget {
  sids?: string[];
  coven?: string[];
  where?: string;
}

export interface ErrandRunCreateRequest {
  module: string;
  input?: Record<string, unknown>;
  timeout_seconds?: number;
  target: ErrandRunTarget;
  concurrency?: number;
  on_failure?: ErrandRunOnFailure;
}

// Record of one child Errand in the Summary (ErrandRunRef). errand_id is empty if
// the Spawner failed before creating the row (NotConnected).
export interface ErrandRunRef {
  sid: string;
  status: string;
  errand_id?: string;
  error_code?: string;
}

// Aggregated ErrandRun result (jsonb column `summary`). counts — flat
// top-level fields, per-host list — `errands[]`.
export interface ErrandRunSummary {
  total: number;
  succeeded: number;
  failed: number;
  cancelled: number;
  errands: ErrandRunRef[];
}

export interface ErrandRunView {
  errand_run_id: string;
  module: string;
  status: ErrandRunStatus;
  scope_size: number;
  current_done?: number;
  concurrency: number;
  on_failure: ErrandRunOnFailure;
  target: ErrandRunTarget;
  started_by_aid?: string;
  started_at: string;
  finished_at?: string;
  summary?: ErrandRunSummary;
}

export interface ErrandRunListEntry {
  errand_run_id: string;
  module: string;
  status: ErrandRunStatus;
  scope_size: number;
  current_done?: number;
  started_at: string;
  finished_at?: string;
  target_preview?: string;
}

export interface ErrandRunListReply {
  items: ErrandRunListEntry[];
  offset: number;
  limit: number;
  total: number;
}

export interface ErrandRunCreateReply {
  errand_run_id: string;
}

// Cadence — recurring scheduled Voyage runs (ADR-046). Types from gen.
export type Cadence = components['schemas']['Cadence'];
export type CadenceCreateRequest = components['schemas']['CadenceCreateRequest'];
export type CadencePatchRequest = components['schemas']['CadencePatchRequest'];
export type CadenceCreateReply = components['schemas']['CadenceCreateReply'];
export type CadenceEnabledReply = components['schemas']['CadenceEnabledReply'];
export type CadenceListReply = components['schemas']['CadenceListReply'];
export type CadenceScheduleKind = NonNullable<Cadence['schedule_kind']>;
export type CadenceOverlapPolicy = NonNullable<Cadence['overlap_policy']>;

// Voyage — unified batch run (ADR-043). Types from gen (sources of truth).
export type VoyageStatus = NonNullable<components['schemas']['Voyage']['status']>;
export type VoyageKind = NonNullable<components['schemas']['Voyage']['kind']>;
export type VoyageOnFailure = NonNullable<components['schemas']['VoyageCreateRequest']['on_failure']>;
export type VoyageTarget = components['schemas']['VoyageTarget'];
export type VoyageCreateRequest = components['schemas']['VoyageCreateRequest'];
export type VoyageCreateReply = components['schemas']['VoyageCreateReply'];
// VoyageNotify — one-off subscription for run notifications (ADR-052(g) amendment N2).
export type VoyageNotify = components['schemas']['VoyageNotify'];
// Allowed terminal events for the `on` field (completed/failed/partial).
export type VoyageNotifyOn = NonNullable<VoyageNotify['on']>[number];
export type VoyageSummary = components['schemas']['VoyageSummary'];
export type Voyage = components['schemas']['Voyage'];
export type VoyageListReply = components['schemas']['VoyageListReply'];
export type VoyageCancelReply = components['schemas']['VoyageCancelReply'];
export type VoyageTargetEntry = components['schemas']['VoyageTargetEntry'];
export type VoyageTargetStatus = VoyageTargetEntry['status'];
export type VoyageTargetsReply = components['schemas']['VoyageTargetsReply'];
export type VoyagePreviewReply = components['schemas']['VoyagePreviewReply'];

export interface ListVoyagesQuery {
  kind?: VoyageKind;
  status?: VoyageStatus[];
  offset?: number;
  limit?: number;
}

// Push-providers (ADR-032 amendment 2026-05-26, S7-2). Narrow aliases.
export type PushProvider = components['schemas']['PushProvider'];
export type PushProviderListReply = components['schemas']['PushProviderListReply'];

// Cloud-Provider — cloud provider registry (ADR-017). Types from gen.
export type Provider = components['schemas']['Provider'];
export type ProviderCreateRequest = components['schemas']['ProviderCreateRequest'];
export type ProviderListReply = components['schemas']['ProviderListReply'];

// Synod — groups of Archons (ADR-049). Types from gen.
export type SynodView = components['schemas']['SynodView'];
export type SynodListReply = components['schemas']['SynodListReply'];
export type SynodCreateRequest = components['schemas']['SynodCreateRequest'];
export type SynodUpdateRequest = components['schemas']['SynodUpdateRequest'];
export type SynodGrantRoleRequest = components['schemas']['SynodGrantRoleRequest'];

// Herald — notification delivery channel (ADR-052, S5). Types from gen.
export type Herald = components['schemas']['Herald'];
export type HeraldCreateRequest = components['schemas']['HeraldCreateRequest'];
export type HeraldUpdateRequest = components['schemas']['HeraldUpdateRequest'];
export type HeraldListReply = components['schemas']['HeraldListReply'];

// HeraldTypeCatalog — catalog of Herald-channel types and their config fields (ADR-052
// amendment, ADR-042 no-hardcode). GET /v1/herald-types — single source of
// truth for the UI form (don't hardcode the set of types/fields).
export type HeraldTypeCatalogReply = components['schemas']['HeraldTypeCatalogReply'];
export type HeraldTypeCatalogEntry = components['schemas']['HeraldTypeCatalogEntry'];
export type HeraldTypeFieldSpec = components['schemas']['HeraldTypeFieldSpec'];

// Tiding — notification subscription rule (ADR-052, S5). Types from gen.
export type Tiding = components['schemas']['Tiding'];
export type TidingCreateRequest = components['schemas']['TidingCreateRequest'];
export type TidingUpdateRequest = components['schemas']['TidingUpdateRequest'];
export type TidingListReply = components['schemas']['TidingListReply'];

// EventTypeCatalog — catalog of allowed event-types for Tiding (ADR-042, ADR-052).
// GET /v1/event-types → areas (glob subscriptions) + point_events (point-in-time).
export type EventTypeCatalogReply = components['schemas']['EventTypeCatalogReply'];
export type EventTypeArea = components['schemas']['EventTypeArea'];
export type EventTypePoint = components['schemas']['EventTypePoint'];

// GET /v1/me/permissions — effective permissions of the current Archon (permission-aware UI).
export type MyPermission = components['schemas']['MyPermission'];
export type MyPermissionsReply = components['schemas']['MyPermissionsReply'];

export type RoleView = components['schemas']['RoleView'];
export type RoleListReply = components['schemas']['RoleListReply'];
export type RoleCreateRequest = components['schemas']['RoleCreateRequest'];
export type RolePermissionsUpdateRequest = components['schemas']['RolePermissionsUpdateRequest'];
export type GrantOperatorRequest = components['schemas']['GrantOperatorRequest'];

// Permissions catalog (GET /v1/permissions, ADR-042).
// Types come from the generated types.gen.ts (gen:api synced vendor/openapi).
export type PermissionAction = components['schemas']['PermissionAction'];
// PermissionCatalogItem — name from the schema. PermissionResource — alias for components.
export type PermissionCatalogItem = components['schemas']['PermissionCatalogItem'];
export type PermissionResource = PermissionCatalogItem;
export type PermissionCatalogReply = components['schemas']['PermissionCatalogReply'];

export type ServiceView = components['schemas']['ServiceView'];
export type ServiceListReply = components['schemas']['ServiceListReply'];
export type ServiceRegisterRequest = components['schemas']['ServiceRegisterRequest'];
export type ServiceUpdateRequest = components['schemas']['ServiceUpdateRequest'];

// Service state_schema metadata (UI Schema explorer). GET /v1/services/{name}/state-schema.
export type ServiceStateSchemaReply = components['schemas']['ServiceStateSchemaReply'];
export type StateSchemaMigration = components['schemas']['StateSchemaMigration'];

// Service dependencies (destiny + modules). GET /v1/services/{name}/dependencies.
export type ServiceDependency = components['schemas']['ServiceDependency'];
export type ServiceDependenciesReply = components['schemas']['ServiceDependenciesReply'];

// Rerun-last — restart the last failed scenario from error_locked (create or operational).
export type IncarnationRerunLastRequest = components['schemas']['IncarnationRerunLastRequest'];
export type IncarnationRerunLastReply = components['schemas']['IncarnationRerunLastReply'];

// Incarnation membership (incarnation_membership, ADR-008 amendment / NIM-124).
// The roster is the relation a run resolves its hosts from — and since NIM-330
// the only editable one: a declared role is a Voice, and coven==name is a label.
// `bound_by_aid` is optional: rows written by a scenario carry no operator.
export type IncarnationMember = components['schemas']['IncarnationMember'];
export type IncarnationMemberListReply = components['schemas']['IncarnationMemberListReply'];
export type IncarnationMemberBindRequest = components['schemas']['IncarnationMemberBindRequest'];
export type IncarnationMemberBindReply = components['schemas']['IncarnationMemberBindReply'];

// Traits-editing (PUT /v1/incarnations/{name}/traits). Source of truth — incarnation.traits
// (ADR-060); projected into souls.traits. Full replacement (full-replace semantics).
export type IncarnationSetTraitsRequest = components['schemas']['IncarnationSetTraitsRequest'];

// NIM-74: local type until the openapi regen (backend will add the /secrets/revealable|reveal path).
// Discovery: which state secrets can be revealed (on click), and under which keys.
export interface RevealableSecretItem {
  secret_id: string;
  label: string;
  state_path: string;
  keys: string[];
}
export interface RevealableSecretsReply {
  items: RevealableSecretItem[] | null;
}
export interface RevealSecretRequest {
  secret_id: string;
  key: string;
}
export interface RevealSecretReply {
  value: string;
}

// Choir + Voice (ADR-044). Host topology within an incarnation.
export type Choir = components['schemas']['Choir'];
export type Voice = components['schemas']['Voice'];
export type ChoirCreateRequest = components['schemas']['ChoirCreateRequest'];
export type VoiceAddRequest = components['schemas']['VoiceAddRequest'];
export type ChoirListReply = components['schemas']['ChoirListReply'];
export type VoiceListReply = components['schemas']['VoiceListReply'];

// Refs / scenarios endpoints are not yet fixed in openapi (being fixed in parallel
// by a backend slice). Local types — narrow contract used by the UI;
// graceful-degraded on 404/501.
export interface ServiceRefInfo {
  name: string;
  type: 'tag' | 'branch';
  commit?: string;
  is_default?: boolean;
}
export interface ServiceRefListReply {
  // key `refs` (not `items`) — matches the backend schema ServiceRefsListReply; nullable.
  refs: ServiceRefInfo[] | null;
}

/**
 * Catalog source of a SID field in a SCENARIO's input_schema. A superset of the
 * module-param discriminator (`ModuleInputSource`): scenario input adds `roster`.
 *
 * The scenario schema travels as a raw map (the keeper does not project it through a
 * typed wire schema), so this type is declared here rather than generated — which is
 * also why it can carry a variant the module contract has no use for.
 *
 * Exactly one variant is active:
 *  - `incarnation_hosts` / `choir` — resolved against an EXISTING incarnation, so they
 *    need an incarnation context and are fetched through module form-prep;
 *  - `roster` — the souls an incarnation is being CREATED on (ADR-081). There is no
 *    incarnation to resolve against yet, so the catalog is the scoped souls list:
 *    free, online hosts inside the covens the form declares.
 */
export type ScenarioInputSource = ModuleInputSource & { roster?: boolean };

// input_schema — flat-map field→property (NOT a JSON-Schema wrapper `{type:'object',properties}`).
// Each property carries its own `required: boolean` (per-field, not a top-level array).
// UI renders simple types (string/integer/number/boolean) per-field; composite
// types (array/object/oneOf/...) → fallback to a JSON textarea.
// ADR-045 S4: pattern/format/source describe the module's UI form (SID-picker, validation).
export interface ScenarioInputSchemaProperty {
  type?: string;
  description?: string;
  required?: boolean;
  /** CEL predicate for required-ness (reactive, like show_when). Field is required when the expression is true. */
  required_when?: string;
  default?: unknown;
  enum?: unknown[];
  /** Regex constraint on the value (ADR-045). */
  pattern?: string;
  /** Semantic string format (sid/hostname/...). */
  format?: string;
  /** Catalog source for the SID-picker (ADR-045). */
  source?: ScenarioInputSource;
  /**
   * List item type (ADR-045 S8b). Present for type=array.
   * Contains a nested ScenarioInputSchemaProperty (recursively).
   * For type=map/object: the map's value type — with a scalar items.type
   * the UI renders a KEY->VALUE editor; without items -> JSON textarea.
   */
  items?: ScenarioInputSchemaProperty;
  /** Field is a large textarea rather than a single-line input (ADR-045 B3). */
  multiline?: boolean;
  /** Example value for the placeholder (ADR-045 B3). */
  example?: string;
  /** Marker for a normalized map type (type=map): scalar items.type -> KEY->VALUE editor. */
  isMap?: boolean;
  /**
   * NIM-243: the module still honors the parameter but it is on its way out.
   * A warning, never a gate — the field stays editable and is still submitted.
   * Carried here (rather than alongside the schema) so it survives
   * paramsToInputSchema, which builds properties from an explicit field list.
   */
  deprecated?: ModuleDeprecation;
  /**
   * Sub-fields of a typed object (NIM-72). Present for a single
   * type=object (AclUser add_user.user) and for items array-of-object.
   * Note: object-level `required` here is an array of required sub-field names
   * (JSON-Schema style), not a boolean; read via a cast.
   */
  properties?: Record<string, ScenarioInputSchemaProperty>;
  /**
   * type=object map (NIM-72): scalar value schema ({type:string}) -> MapEditor;
   * false — typed object (not a map); true/absent — degrade to JSON textarea.
   */
  additional_properties?: ScenarioInputSchemaProperty | boolean;
  /** Sub-object type name (AclUser...) — UI label. */
  'x-type'?: string;
  /**
   * NIM-76: marker for a directives-dictionary field. A truthy value (e.g. "redis") enables
   * inline validation + key typeahead against the service's directive catalog. We validate
   * ONLY marked fields (the redis_settings name is not hardcoded).
   */
  'x-directives'?: string;
  /**
   * NIM-72: field-level required-ness of a $type reference node. For object-$type the
   * `required` key is taken by the array of required children — "the field itself is required"
   * comes via this annotation, and the UI shows `*` based on it.
   */
  'x-required'?: boolean;
  [key: string]: unknown;
}
export type ScenarioInputSchema = Record<string, ScenarioInputSchemaProperty>;

// ScenarioForm types: optional presentation layer for scenario input_schema (ADR-045).
export type ScenarioForm = components['schemas']['ScenarioForm'];
export type IncarnationResolveNameRequest = components['schemas']['IncarnationResolveNameRequest'];
export type IncarnationResolveNameReply = components['schemas']['IncarnationResolveNameReply'];
export type ScenarioFormSection = components['schemas']['ScenarioFormSection'];
export type ScenarioFormField = components['schemas']['ScenarioFormField'];

export interface ServiceScenarioInfo {
  name: string;
  // Backend returns `scenario/<name>/main.yml` — read-only, informational.
  path?: string;
  /** Discriminator: lifecycle (create/destroy/converge) | operational. */
  kind: 'lifecycle' | 'operational';
  /**
   * Runnable by an operator from the Run form (ADR-042, backend field).
   * create=true, destroy=false, operational=true.
   * UI filters by this field, not by hardcoded names.
   * Optional for backward compatibility: an old backend without the field -> fallback to runnableScenarios.
   */
  runnable?: boolean;
  /**
   * Starting scenario for incarnation creation (POST /v1/incarnations).
   * If true — the scenario is offered in the dropdown when creating an incarnation.
   * UI filters create scenarios by this flag (not by hardcoded names).
   */
  create?: boolean;
  description?: string;
  input_schema?: ScenarioInputSchema;
  /**
   * The create scenario composes the incarnation name from its `input:`
   * components instead of the operator typing one, so POST /v1/incarnations must
   * NOT carry `name` (the keeper refuses a request that does).
   *
   * A flag, not the template: the operator is shown the resulting name, not the
   * formula. The name itself comes from `incarnations.resolveName` — the keeper
   * composes, the form displays. Composing here instead would mean a second CEL
   * evaluator producing a different string from the same input, and under an
   * immutable name that is a different identity, arrived at silently.
   *
   * Optional for backward compatibility: an older keeper omits the field, and the
   * form then behaves as it did before — a name is typed.
   */
  composes_name?: boolean;
  /** Optional presentation layer: splits fields into sections with headings. */
  form?: ScenarioForm;
}
// Backend shape: `{ service, ref, scenarios: [...] }` (NOT `{ items: [...] }`).
export interface ServiceScenarioListReply {
  service?: string;
  ref?: string;
  scenarios: ServiceScenarioInfo[];
}

// GET /v1/services/{name}/directives[?ref=&version=] — catalog of allowed
// directive names (redis.conf) by Redis series. directives: series "major.minor" ->
// sorted names. Response is immutable per git-ref (ETag + Cache-Control: immutable);
// cached aggressively (staleTime: Infinity, keyed by service+ref). A service without a catalog
// -> directives:{} + 200. Endpoint is optional — UI graceful-degraded on 404/501.
export interface ServiceDirectivesReply {
  service?: string;
  ref?: string;
  sha1?: string;
  // Series ("8.2") -> sorted directive names; nullable per contract.
  directives: Record<string, string[]> | null;
}

// Oracle: Vigil (Soul-side beacon checks) + Decree (reactor rule). ADR-030.
export type VigilCreateRequest = components['schemas']['VigilCreateRequest'];
export type VigilView = components['schemas']['VigilView'];
export type VigilListReply = components['schemas']['VigilListReply'];
export type DecreeCreateRequest = components['schemas']['DecreeCreateRequest'];
export type DecreeView = components['schemas']['DecreeView'];
export type DecreeListReply = components['schemas']['DecreeListReply'];

// Module catalog (GET /v1/modules, commit 530329d). core from the coremod registry,
// plugin from active plugin_sigils + manifest params. Used by Run->Command
// module-search (replacement for the free-text "custom module").
export type ModuleCatalogItem = components['schemas']['ModuleCatalogItem'];
export type ModuleCatalogReply = components['schemas']['ModuleCatalogReply'];
export type ModuleParam = components['schemas']['ModuleParam'];
export type ModuleInputSource = components['schemas']['ModuleInputSource'];
export type ModuleDeprecation = components['schemas']['ModuleDeprecation'];
export type ModuleKind = NonNullable<ModuleCatalogItem['kind']>;

// form-prep (ADR-045 S4): resolves live SIDs by source (incarnation_hosts/choir) + prefix.
export interface ModuleFormPrepRequest {
  source: {
    incarnation_hosts?: string;
    choir?: { incarnation: string; name: string };
  };
  prefix?: string;
}
export interface ModuleFormPrepReply {
  sids: string[];
  truncated: boolean;
}

export type PluginSigilView = components['schemas']['PluginSigilView'];
export type PluginSigilListReply = components['schemas']['PluginSigilListReply'];
export type PluginSigilAllowRequest = components['schemas']['PluginSigilAllowRequest'];
export type PluginSigilAllowReply = components['schemas']['PluginSigilAllowReply'];

// --- Public-thrown error for the GetSoulprint -> 410 "not received" case. ---

export class SoulprintNotReceivedError extends Error {
  constructor(public sid: string) {
    super(`soulprint not yet received for ${sid}`);
    this.name = 'SoulprintNotReceivedError';
  }
}

// --- API ---

// Filter predicate over state fields: state.<field>=<op>:<value>.
// op is one of eq | ne | gt | gte | lt | lte. Backend validates numeric op + a non-numeric
// value -> 422 (non-numeric value in a numeric op). UI treats 422 as a field-level error.
export interface StateFilterPredicate {
  field: string;
  op: 'eq' | 'ne' | 'gt' | 'gte' | 'lt' | 'lte';
  value: string;
}

export interface ListIncarnationsQuery {
  service?: string;
  status?: IncarnationStatus;
  coven?: string;
  offset?: number;
  limit?: number;
  // Server-side sorting: sort = column name (name | status | created_at | state.<field>).
  // sort_dir = asc | desc.
  sort?: string;
  sort_dir?: 'asc' | 'desc';
  // Filters over state fields. Serialized as state.<field>=<op>:<value>.
  state_filters?: StateFilterPredicate[];
}

export interface ListSoulsQuery {
  coven?: string[];
  status?: SoulStatus;
  transport?: SoulTransport;
  /**
   * Only hosts belonging to no incarnation — the free souls a create scenario can
   * roll onto (ADR-081). A membership question, not a label one.
   */
  unassigned?: boolean;
  /** Only SIDs with this prefix (autocomplete). Matched literally by the server. */
  sid_prefix?: string;
  offset?: number;
  limit?: number;
  cursor?: string;
}

/** Filters of `souls.listAll` — the page window is the loop's business, not the caller's. */
export type ListAllSoulsQuery = Omit<ListSoulsQuery, 'offset' | 'limit' | 'cursor'>;

export interface SoulListAllReply {
  /** Every soul the loop read, deduplicated by SID, in server order. */
  items: SoulListEntry[];
  /** `total` of the last page read — the exact size of the set within the operator's scope. */
  total: number;
  /** The cap stopped the loop before the set ran out: `items` is a prefix, not the set. */
  truncated: boolean;
}

/**
 * Largest page `GET /v1/souls` serves. Asking for more is a 400 (`invalid limit
 * 1001: must be <= 1000`), not a silent clamp, so this is the loop's step — not a
 * number to raise.
 */
const SOULS_MAX_PAGE = 1000;

/**
 * Pages `souls.listAll` will read before giving up and reporting `truncated`.
 * 20 x 1000 covers any fleet we have seen; past it the caller says out loud that
 * it resolved against a prefix rather than quietly pretending otherwise.
 */
const SOULS_ALL_MAX_PAGES = 20;

function fetchSoulsPage(q: ListSoulsQuery = {}): Promise<SoulListReply> {
  return apiGet<SoulListReply>('/v1/souls', {
    query: {
      coven: q.coven,
      status: q.status,
      transport: q.transport,
      // Omitted rather than sent as `false`: an absent filter and a disabled one
      // mean the same thing to the server, and a bare `?unassigned=false` in the
      // URL reads like a deliberate "show me the busy ones".
      unassigned: q.unassigned ? true : undefined,
      sid_prefix: q.sid_prefix,
      offset: q.offset,
      limit: q.limit,
      cursor: q.cursor,
    },
  });
}

async function listAllSouls(
  q: ListAllSoulsQuery,
  maxPages: number,
): Promise<SoulListAllReply> {
  const items: SoulListEntry[] = [];
  const seen = new Set<string>();
  let total = 0;
  // Offset advances by the page size, not by items.length: dedup can drop rows,
  // and re-reading the window they came from would loop on the same page forever.
  let offset = 0;

  for (let page = 0; page < maxPages; page += 1) {
    const reply = await fetchSoulsPage({ ...q, offset, limit: SOULS_MAX_PAGE });
    total = reply.total;
    const batch = reply.items ?? [];
    for (const soul of batch) {
      if (seen.has(soul.sid)) continue;
      seen.add(soul.sid);
      items.push(soul);
    }
    // The envelope still carries the two keyset fields the souls list stopped
    // filling when its keyset mode was removed — the server builds one reply, by
    // offset, with an exact total, and `omitempty` drops both. If either ever
    // shows up again, this walk is reading a set it cannot page: `total` is an
    // estimate, so `offset >= total` would end the loop early, and the offsets
    // themselves may mean nothing. Say `truncated` and let the caller warn rather
    // than hand back a prefix labelled complete — which is the whole bug this
    // function exists to remove.
    if (reply.next_cursor !== undefined || reply.total_approximate === true) {
      return { items, total, truncated: true };
    }
    offset += SOULS_MAX_PAGE;
    if (batch.length < SOULS_MAX_PAGE || offset >= total) {
      return { items, total, truncated: false };
    }
  }
  return { items, total, truncated: true };
}

export const keeperApi = {
  // health-probe, handy as a "is the token valid?" check (via /v1/incarnations).
  ping: () => apiGet<IncarnationListReply>('/v1/incarnations', { query: { limit: 1 } }),

  incarnations: {
    list: (q: ListIncarnationsQuery = {}) => {
      // Serialize state predicates into repeated query params:
      // state.<field>=<op>:<value>. buildUrl in client.ts supports multi-value.
      const stateParams: Record<string, string[]> = {};
      for (const pred of q.state_filters ?? []) {
        const key = `state.${pred.field}`;
        const val = `${pred.op}:${pred.value}`;
        if (!stateParams[key]) stateParams[key] = [];
        stateParams[key].push(val);
      }
      return apiGet<IncarnationListReply>('/v1/incarnations', {
        query: {
          service: q.service,
          status: q.status,
          coven: q.coven,
          offset: q.offset,
          limit: q.limit,
          sort: q.sort,
          sort_dir: q.sort_dir,
          ...stateParams,
        },
      });
    },
    get: (name: string) =>
      apiGet<IncarnationGetReply>(`/v1/incarnations/${encodeURIComponent(name)}`),
    // GET /v1/incarnations/{name}/telemetry — host-vitals aggregate over the coven's hosts
    // (latest+stale per host, no window). NIM-86. Empty souls / out of scope → hosts:[].
    telemetry: (name: string) =>
      apiGet<IncarnationTelemetryReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/telemetry`,
      ),
    create: (body: IncarnationCreateRequest) =>
      apiSend<IncarnationCreateReply>('/v1/incarnations', 'POST', { body }),
    // POST /v1/incarnations/resolve-name — what name would a create with this input
    // compose, is it a legal name, and is it free. Creates nothing; the create
    // re-checks everything. Called on a debounce as the operator fills the identity
    // components of a `composes_name` scenario.
    //
    // `covens` is not part of the composition — it is sent so the permission check
    // scopes the preview exactly as it scopes the create it previews; without it a
    // coven-scoped operator would be refused on every keystroke for a create that
    // would have succeeded.
    resolveName: (body: IncarnationResolveNameRequest) =>
      apiSend<IncarnationResolveNameReply>('/v1/incarnations/resolve-name', 'POST', { body }),
    // API behavior: if `wave` is present in the request, IncarnationRunTideReply is returned,
    // otherwise — the classic IncarnationRunReply. A caller using wave must do its own
    // type-narrowing by the presence of `tide_id`. The existing /incarnations/:name -> RunScenarioForm
    // calls WITHOUT wave and keeps working as before.
    // dryRun — classic only (not Tide): adds `?dry_run=true` (canonical soulctl
    // path). Backend ORs the query flag with the body field; we send it via query.
    runScenario: (
      name: string,
      scenario: string,
      body: IncarnationRunRequest = {},
      opts: { dryRun?: boolean } = {},
    ) =>
      apiSend<IncarnationRunReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/scenarios/${encodeURIComponent(scenario)}`,
        'POST',
        { body, query: opts.dryRun ? { dry_run: true } : undefined },
      ),
    history: (name: string, q: { offset?: number; limit?: number } = {}) =>
      apiGet<IncarnationHistoryReply>(`/v1/incarnations/${encodeURIComponent(name)}/history`, {
        query: { offset: q.offset, limit: q.limit },
      }),
    // GET /v1/incarnations/{name}/runs — list of runs (apply_run, NOT Voyage):
    // rollup of apply_runs by apply_id, status applying/success/failed/cancelled.
    runs: (name: string, q: { offset?: number; limit?: number } = {}) =>
      apiGet<IncarnationRunsReply>(`/v1/incarnations/${encodeURIComponent(name)}/runs`, {
        query: { offset: q.offset, limit: q.limit },
      }),
    // GET /v1/incarnations/{name}/runs/{apply_id} — run details: per-host
    // status slice + location of the failed task (task_idx/plan_index/error_summary).
    // NOT the full per-task list (TaskEvent is aggregated on the Soul, ADR-012).
    runDetail: (name: string, applyId: string) =>
      apiGet<RunDetailReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/runs/${encodeURIComponent(applyId)}`,
      ),
    // GET /v1/incarnations/{name}/runs/{apply_id}/tasks (NIM-37) — per-task run
    // progress (Schema-2): server joins the plan with per-host outcomes. Live AND history
    // in one response. 404/501 (backend slice not deployed) -> graceful fallback to
    // per-host + audit.
    runTasks: (name: string, applyId: string) =>
      apiGet<RunTasksReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/runs/${encodeURIComponent(applyId)}/tasks`,
      ),
    unlock: (name: string, body: IncarnationUnlockRequest) =>
      apiSend<IncarnationUnlockReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/unlock`,
        'POST',
        { body },
      ),
    upgrade: (name: string, body: IncarnationUpgradeRequest) =>
      apiSend<IncarnationUpgradeReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/upgrade`,
        'POST',
        { body },
      ),
    // GET /v1/incarnations/{name}/upgrade-paths (NIM-34). Without `to` — registry tags
    // + is_current; with `to` — analysis of a single target (direction/found-legacy/state migrations).
    upgradePaths: (name: string, to?: string) =>
      apiGet<IncarnationUpgradePathsReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/upgrade-paths`,
        { query: to ? { to } : undefined },
      ),
    // DELETE /v1/incarnations/{name}?allow_destroy=<bool>. allow_destroy=true —
    // teardown without a scenario (force), false — normal path via the `destroy` scenario.
    destroy: (name: string, allowDestroy: boolean) =>
      apiSend<IncarnationDestroyReply>(
        `/v1/incarnations/${encodeURIComponent(name)}`,
        'DELETE',
        { query: { allow_destroy: allowDestroy } },
      ),
    // POST /v1/incarnations/{name}/rerun-last — atomic unlock + restart of the
    // last failed scenario (create or operational) with the saved input. 202 ->
    // IncarnationRerunLastReply (incl. scenario). 404 no incarnation, 403 no
    // permission, 409 status is not error_locked OR the failed run's input is unavailable
    // (ErrRerunInputUnavailable — purged by retention), 422 validation.
    rerunLast: (name: string, body: IncarnationRerunLastRequest) =>
      apiSend<IncarnationRerunLastReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/rerun-last`,
        'POST',
        { body },
      ),
    // GET /v1/incarnations/{name}/members — the membership roster. Permission
    // incarnation.get, but the rows are NARROWED to the hosts inside the caller's
    // soul scope: a host the operator may not see is absent from the reply, and
    // that is the contract, not a gap in the UI.
    members: (name: string) =>
      apiGet<IncarnationMemberListReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/members`,
      ),
    // POST /v1/incarnations/{name}/members — bind already-onboarded, connected
    // hosts. Permission incarnation.bind-member. Idempotent, and the reply splits
    // what this call wrote (bound) from what was already there (already_member).
    // ALL-OR-NOTHING on the per-host gate: one SID outside the caller's soul
    // scope rejects the whole request with 403. 422 covers two distinct causes —
    // an unknown SID and a host that is not connected.
    bindMembers: (name: string, sids: string[]) =>
      apiSend<IncarnationMemberBindReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/members`,
        'POST',
        { body: { sids } satisfies IncarnationMemberBindRequest },
      ),
    // DELETE /v1/incarnations/{name}/members/{sid} — unbind one host.
    // Permission incarnation.unbind-member. Idempotent (204 even for a
    // non-member); the host leaves the roster of every future run.
    unbindMember: (name: string, sid: string) =>
      apiSend<void>(
        `/v1/incarnations/${encodeURIComponent(name)}/members/${encodeURIComponent(sid)}`,
        'DELETE',
      ),
    // PUT /v1/incarnations/{name}/traits — full replacement of incarnation.traits (ADR-060).
    // Source of truth; projected into souls.traits of member hosts.
    // Permission: incarnation.traits-set. 200 -> updated incarnation.
    setTraits: (name: string, body: IncarnationSetTraitsRequest) =>
      apiSend<IncarnationGetReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/traits`,
        'PUT',
        { body },
      ),
    // NIM-74: discovery of an incarnation's revealable secrets. GET .../secrets/revealable.
    // items[] is empty if there's nothing to reveal; 404 if the incarnation is out of scope — UI graceful.
    revealableSecrets: (name: string) =>
      apiGet<RevealableSecretsReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/secrets/revealable`,
      ),
    // NIM-74: reveal a single value on click (lazy, not cached). POST .../secrets/reveal.
    // 200 -> {value}; 403 missing incarnation.view-secrets permission; 404 no such key/value.
    revealSecret: (name: string, body: RevealSecretRequest) =>
      apiSend<RevealSecretReply>(
        `/v1/incarnations/${encodeURIComponent(name)}/secrets/reveal`,
        'POST',
        { body },
      ),
  },

  // Global run-view across all incarnations (apply_run, NOT Voyage). Permission incarnation.history.
  // sort/sort_dir — server-side column sorting (whitelist
  // started_at|finished_at|status|incarnation|scenario|service; default started_at desc; invalid -> 422).
  runs: {
    list: (
      q: {
        status?: RunStatus;
        incarnation?: string;
        service?: string;
        q?: string;
        started_after?: string;
        started_before?: string;
        offset?: number;
        limit?: number;
        sort?: string;
        sort_dir?: 'asc' | 'desc';
      } = {},
    ) =>
      apiGet<RunsListReply>('/v1/runs', {
        query: {
          status: q.status,
          incarnation: q.incarnation,
          service: q.service,
          q: q.q,
          started_after: q.started_after,
          started_before: q.started_before,
          offset: q.offset,
          limit: q.limit,
          sort: q.sort,
          sort_dir: q.sort_dir,
        },
      }),
    stats: () => apiGet<RunsStatsReply>('/v1/runs/stats'),
  },

  // Choir/Voice — host topology within an incarnation (ADR-044).
  choirs: {
    // GET /v1/incarnations/{name}/choirs -> ChoirListReply (sorted by choir_name).
    list: (incarnationName: string) =>
      apiGet<ChoirListReply>(
        `/v1/incarnations/${encodeURIComponent(incarnationName)}/choirs`,
      ),
    // POST /v1/incarnations/{name}/choirs -> 201 Choir.
    create: (incarnationName: string, body: ChoirCreateRequest) =>
      apiSend<Choir>(
        `/v1/incarnations/${encodeURIComponent(incarnationName)}/choirs`,
        'POST',
        { body },
      ),
    // DELETE /v1/incarnations/{name}/choirs/{choir} -> 204 (CASCADE deletes Voices).
    delete: (incarnationName: string, choirName: string) =>
      apiSend<void>(
        `/v1/incarnations/${encodeURIComponent(incarnationName)}/choirs/${encodeURIComponent(choirName)}`,
        'DELETE',
      ),
    // GET .../choirs/{choir}/voices -> VoiceListReply.
    listVoices: (incarnationName: string, choirName: string) =>
      apiGet<VoiceListReply>(
        `/v1/incarnations/${encodeURIComponent(incarnationName)}/choirs/${encodeURIComponent(choirName)}/voices`,
      ),
    // POST .../choirs/{choir}/voices {sid, role?, position?} -> 201 Voice.
    // 422 ErrNotMembers if the SID is not a member of the incarnation.
    addVoice: (incarnationName: string, choirName: string, body: VoiceAddRequest) =>
      apiSend<Voice>(
        `/v1/incarnations/${encodeURIComponent(incarnationName)}/choirs/${encodeURIComponent(choirName)}/voices`,
        'POST',
        { body },
      ),
    // DELETE .../choirs/{choir}/voices/{sid} -> 204.
    removeVoice: (incarnationName: string, choirName: string, sid: string) =>
      apiSend<void>(
        `/v1/incarnations/${encodeURIComponent(incarnationName)}/choirs/${encodeURIComponent(choirName)}/voices/${encodeURIComponent(sid)}`,
        'DELETE',
      ),
  },

  // HA topology of the Keeper cluster (Conclave registry) + self_health of the current instance.
  cluster: {
    get: () => apiGet<ClusterReply>('/v1/cluster'),
  },

  souls: {
    list: (q: ListSoulsQuery = {}) => fetchSoulsPage(q),
    /**
     * Every soul in the operator's scope, not the first page of them.
     *
     * `GET /v1/souls` serves at most 1000 rows per request and pages by offset with
     * an exact `total` (there is no keyset mode on this endpoint), so "all souls"
     * is a loop. A caller that asks once and filters the answer client-side does
     * not resolve a target set — it resolves a page, and every host past row 1000
     * drops out of the run with nothing on screen to say so (NIM-448).
     *
     * Stops early on the first short page (offset paging only under-fills at the
     * end of the set) and dedupes by SID, because a registration landing mid-loop
     * shifts rows between pages — the list is ordered `registered_at DESC, sid ASC`,
     * so a new host prepends. Past `maxPages` it stops and says `truncated`: a
     * bounded read the caller can be honest about beats an unbounded one.
     */
    listAll: (q: ListAllSoulsQuery = {}, maxPages = SOULS_ALL_MAX_PAGES) =>
      listAllSouls(q, maxPages),
    get: (sid: string) => apiGet<SoulListEntry>(`/v1/souls/${encodeURIComponent(sid)}`),
    // GET /v1/souls/{sid}/telemetry — host-vitals: latest + window (sparklines,
    // newest-first) + freshness (collected_at/received_at, stale). NIM-86.
    telemetry: (sid: string) =>
      apiGet<SoulTelemetryReply>(`/v1/souls/${encodeURIComponent(sid)}/telemetry`),
    // GET /v1/souls/stats — summary of by_status/by_transport/by_coven + total +
    // stale_count for the Souls Overview. Scoped visibility (ADR-047). Read-only.
    stats: () => apiGet<SoulStatsReply>('/v1/souls/stats'),
    // GET /v1/souls/{sid}/history — per-host operation timeline (scenario apply_runs
    // + ad-hoc errands), merged by started_at DESC. type — multi-value OR (scenario|errand).
    history: (sid: string, q: ListSoulHistoryQuery = {}) =>
      apiGet<SoulHistoryReply>(`/v1/souls/${encodeURIComponent(sid)}/history`, {
        query: { type: q.type, since: q.since, offset: q.offset, limit: q.limit },
      }),
    // 410 -> SoulprintNotReceivedError (the Soul record exists, facts haven't arrived yet).
    // Other errors are rethrown as ApiError.
    getSoulprint: async (sid: string): Promise<SoulprintReadReply> => {
      try {
        return await apiGet<SoulprintReadReply>(
          `/v1/souls/${encodeURIComponent(sid)}/soulprint`,
        );
      } catch (err) {
        if (
          err &&
          typeof err === 'object' &&
          'status' in err &&
          (err as { status: number }).status === 410
        ) {
          throw new SoulprintNotReceivedError(sid);
        }
        throw err;
      }
    },
    // POST /v1/souls/{sid}/issue-token?force=<bool>. 200 -> SoulIssueTokenReply.
    // plain bootstrap_token is returned once. 409 if active without force=true,
    // 422 if transport: ssh.
    issueToken: (sid: string, force = false) =>
      apiSend<SoulIssueTokenReply>(
        `/v1/souls/${encodeURIComponent(sid)}/issue-token`,
        'POST',
        { query: { force } },
      ),
    // POST /v1/souls — register a new host. 201 -> SoulCreateReply.
    // bootstrap_token is present only for transport: agent (one-time, never log).
    // 409 -> SID already taken; 422 -> invalid SID/transport.
    create: (body: SoulCreateRequest) =>
      apiSend<SoulCreateReply>('/v1/souls', 'POST', { body }),
    // POST /v1/souls/coven. Bulk coven-assign: mode=append/remove (label) or
    // mode=replace (labels). Chunked with a per-chunk commit — status=completed|partial.
    bulkAssignCoven: (body: SoulCovenAssignRequest) =>
      apiSend<SoulCovenAssignReply>('/v1/souls/coven', 'POST', { body }),
    // POST /v1/souls/traits. Bulk trait-assign: mode=merge/replace/remove.
    // dry_run — count matched without an UPDATE. Permission soul.traits-assign.
    assignTraits: (body: SoulTraitsAssignRequest, dryRun = false) =>
      apiSend<SoulTraitsAssignReply>('/v1/souls/traits', 'POST', {
        body,
        query: dryRun ? { dry_run: true } : undefined,
      }),
    // POST /v1/souls/{sid}/exec. 200 -> ErrandResult (sync), 202 -> ErrandAccepted (async).
    // Return a discriminated union — the caller decides whether to poll or render.
    exec: async (
      sid: string,
      body: ErrandRunRequest,
    ): Promise<{ kind: 'sync'; result: ErrandResult } | { kind: 'async'; accepted: ErrandAccepted }> => {
      const res = await fetch(`/v1/souls/${encodeURIComponent(sid)}/exec`, {
        method: 'POST',
        headers: buildAuthHeaders(),
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        let problem: { type?: string; title?: string; detail?: string } = {};
        try { problem = await res.json(); } catch { /* empty */ }
        if (res.status === 401) tokenStoreClear();
        throw new ApiError(res.status, problem.type ?? 'about:blank', problem.title ?? res.statusText, problem.detail ?? '');
      }
      const payload = (await res.json()) as ErrandResult | ErrandAccepted;
      if (res.status === 202) {
        return { kind: 'async', accepted: payload as ErrandAccepted };
      }
      return { kind: 'sync', result: payload as ErrandResult };
    },
  },

  errands: {
    list: (q: ListErrandsQuery = {}) =>
      apiGet<ErrandListReply>('/v1/errands', {
        query: {
          sid: q.sid,
          status: q.status,
          started_after: q.started_after,
          module: q.module,
          offset: q.offset,
          limit: q.limit,
        },
      }),
    // 200 -> ErrandResult, 202 -> ErrandAccepted. Distinguished by status, not the HTTP code.
    get: (errandId: string) =>
      apiGet<ErrandResult | ErrandAccepted>(`/v1/errands/${encodeURIComponent(errandId)}`),
  },

  audit: {
    list: (q: ListAuditQuery = {}) =>
      apiGet<AuditEventListReply>('/v1/audit', {
        query: {
          type: q.type,
          source: q.source,
          archon_aid: q.archon_aid,
          correlation_id: q.correlation_id,
          payload_herald: q.payload_herald,
          payload_voyage: q.payload_voyage,
          started_after: q.started_after,
          started_before: q.started_before,
          offset: q.offset,
          limit: q.limit,
        },
      }),
  },

  push: {
    // 202 -> PushApplyReply.
    apply: (body: PushApplyRequest) =>
      apiSend<PushApplyReply>('/v1/push/apply', 'POST', { body }),
    get: (applyId: string) => apiGet<PushApplyView>(`/v1/push/${encodeURIComponent(applyId)}`),
  },

  // Push-runs global list (UI-4, openapi commit 795ceba). Compact entry form
  // with summary_counts; per-host hosts[] — via push.get(apply_id).
  pushRuns: {
    list: (q: ListPushRunsQuery = {}) =>
      apiGet<PushRunListReply>('/v1/push-runs', {
        query: {
          status: q.status,
          ssh_provider: q.ssh_provider,
          offset: q.offset,
          limit: q.limit,
        },
      }),
  },

  // Tide-runs (ADR-040 W-4). Global list + detail-snapshot.
  // Tide API removed (Voyage replaces Tide, ADR-043).

  // Provisioning-policy — list of allowed operator-creation methods (ADR-058 Part B).
  provisioning: {
    // GET /v1/provisioning-policy -> ProvisioningPolicyReply.
    // policy_set=false -> policy not set (all methods allowed by default).
    getPolicy: () => apiGet<ProvisioningPolicyReply>('/v1/provisioning-policy'),
    // PUT /v1/provisioning-policy -> ProvisioningPolicyReply (replace semantics).
    // 422 — empty list (anti-lockout) or a method outside {user,ldap,oidc}.
    updatePolicy: (body: ProvisioningPolicyUpdateRequest) =>
      apiSend<ProvisioningPolicyReply>('/v1/provisioning-policy', 'PUT', { body }),
  },

  operators: {
    // 200 -> OperatorListReply (paged + auth_method/revoked/q filters).
    // q — full-text over aid/display_name (backend param added in parallel;
    // until the gen:api regen the type is extended locally in ListOperatorsQuery).
    list: (query: ListOperatorsQuery = {}) =>
      apiGet<OperatorListReply>('/v1/operators', {
        query: {
          auth_method: query.auth_method,
          revoked: query.revoked,
          q: query.q,
          offset: query.offset,
          limit: query.limit,
        },
      }),
    // 200 -> Operator (detail).
    get: (aid: string) => apiGet<Operator>(`/v1/operators/${encodeURIComponent(aid)}`),
    // 201 -> OperatorCreateReply (including jwt — returned once).
    create: (body: OperatorCreateRequest) =>
      apiSend<OperatorCreateReply>('/v1/operators', 'POST', { body }),
    // 204 — no body returned.
    revoke: (aid: string, body: OperatorRevokeRequest = {}) =>
      apiSend<void>(`/v1/operators/${encodeURIComponent(aid)}/revoke`, 'POST', { body }),
    // 200 -> IssueTokenReply (jwt returned once).
    issueToken: (aid: string) =>
      apiSend<IssueTokenReply>(`/v1/operators/${encodeURIComponent(aid)}/issue-token`, 'POST'),
  },

  roles: {
    list: () => apiGet<RoleListReply>('/v1/roles'),
    create: (body: RoleCreateRequest) =>
      apiSend<void>('/v1/roles', 'POST', { body }),
    delete: (name: string) =>
      apiSend<void>(`/v1/roles/${encodeURIComponent(name)}`, 'DELETE'),
    updatePermissions: (name: string, body: RolePermissionsUpdateRequest) =>
      apiSend<void>(`/v1/roles/${encodeURIComponent(name)}/permissions`, 'PATCH', { body }),
    grantOperator: (name: string, body: GrantOperatorRequest) =>
      apiSend<void>(`/v1/roles/${encodeURIComponent(name)}/operators`, 'POST', { body }),
    revokeOperator: (name: string, aid: string) =>
      apiSend<void>(
        `/v1/roles/${encodeURIComponent(name)}/operators/${encodeURIComponent(aid)}`,
        'DELETE',
      ),
  },

  permissions: {
    list: () => apiGet<PermissionCatalogReply>('/v1/permissions'),
    // GET /v1/me/permissions — effective permissions of the current Archon (permission-aware UI, ADR-042).
    listMy: () => apiGet<MyPermissionsReply>('/v1/me/permissions'),
  },

  // Synod — groups of Archons that bundle roles (ADR-049).
  synods: {
    // GET /v1/synods -> SynodListReply (list with members + roles).
    list: () => apiGet<SynodListReply>('/v1/synods'),
    // POST /v1/synods -> 201. 409 synod-already-exists.
    create: (body: SynodCreateRequest) =>
      apiSend<void>('/v1/synods', 'POST', { body }),
    // PATCH /v1/synods/{name} -> 204. Changes only description (name immutable).
    update: (name: string, body: SynodUpdateRequest) =>
      apiSend<void>(`/v1/synods/${encodeURIComponent(name)}`, 'PATCH', { body }),
    // DELETE /v1/synods/{name} -> 204. 409 synod-builtin / would-lock-out-cluster.
    delete: (name: string) =>
      apiSend<void>(`/v1/synods/${encodeURIComponent(name)}`, 'DELETE'),
    operators: {
      // POST /v1/synods/{name}/operators -> 201. body: {aid}.
      add: (name: string, aid: string) =>
        apiSend<void>(`/v1/synods/${encodeURIComponent(name)}/operators`, 'POST', { body: { aid } }),
      // DELETE /v1/synods/{name}/operators/{aid} -> 204.
      remove: (name: string, aid: string) =>
        apiSend<void>(
          `/v1/synods/${encodeURIComponent(name)}/operators/${encodeURIComponent(aid)}`,
          'DELETE',
        ),
    },
    roles: {
      // POST /v1/synods/{name}/roles -> 201. body: {role}.
      grant: (name: string, roleName: string) =>
        apiSend<void>(`/v1/synods/${encodeURIComponent(name)}/roles`, 'POST', {
          body: { role: roleName } satisfies SynodGrantRoleRequest,
        }),
      // DELETE /v1/synods/{name}/roles/{role_name} -> 204.
      revoke: (name: string, roleName: string) =>
        apiSend<void>(
          `/v1/synods/${encodeURIComponent(name)}/roles/${encodeURIComponent(roleName)}`,
          'DELETE',
        ),
    },
  },

  services: {
    list: () => apiGet<ServiceListReply>('/v1/services'),
    get: (name: string) =>
      apiGet<ServiceView>(`/v1/services/${encodeURIComponent(name)}`),
    register: (body: ServiceRegisterRequest) =>
      apiSend<ServiceView>('/v1/services', 'POST', { body }),
    update: (name: string, body: ServiceUpdateRequest) =>
      apiSend<ServiceView>(`/v1/services/${encodeURIComponent(name)}`, 'PATCH', { body }),
    deregister: (name: string) =>
      apiSend<void>(`/v1/services/${encodeURIComponent(name)}`, 'DELETE'),
    // GET /v1/services/{name}/refs — git tags + branches. Endpoint is optional
    // (being fixed in parallel by a backend slice); UI graceful-degraded on 404/501.
    listRefs: (name: string) =>
      apiGet<ServiceRefListReply>(`/v1/services/${encodeURIComponent(name)}/refs`),
    // GET /v1/services/{name}/scenarios[?ref=...] — scenario catalog by git-ref.
    // If ref is not given — service.ref. Endpoint is optional (see listRefs).
    listScenarios: (name: string, ref?: string) =>
      apiGet<ServiceScenarioListReply>(
        `/v1/services/${encodeURIComponent(name)}/scenarios`,
        { query: { ref } },
      ),
    // GET /v1/services/{name}/directives[?ref=&version=] — catalog of Redis directive names
    // by series (for inline validation/typeahead of redis_settings). Cache immutable by git-ref;
    // version — advisory (series is chosen client-side). Endpoint is optional — graceful on 404/501.
    listDirectives: (name: string, opts: { ref?: string; version?: string } = {}) =>
      apiGet<ServiceDirectivesReply>(
        `/v1/services/${encodeURIComponent(name)}/directives`,
        { query: { ref: opts.ref, version: opts.version } },
      ),
    // GET /v1/services/{name}/state-schema[?ref=...] — state_schema metadata
    // (current state_schema_version + optional schema declaration + list of migrations).
    // Endpoint is optional for old Keeper deploys — UI graceful-degraded on 404/501.
    getStateSchema: (name: string, ref?: string) =>
      apiGet<ServiceStateSchemaReply>(
        `/v1/services/${encodeURIComponent(name)}/state-schema`,
        { query: { ref } },
      ),
    // GET /v1/services/{name}/dependencies — destiny and module dependencies of the service
    // with their git-refs (ADR-007). Endpoint is optional — UI graceful-degraded on 404/501.
    getDependencies: (name: string) =>
      apiGet<ServiceDependenciesReply>(`/v1/services/${encodeURIComponent(name)}/dependencies`),
  },

  // Oracle: Vigil registry (Soul-side beacon checks). ADR-030.
  vigils: {
    list: (q: ListPagedQuery = {}) =>
      apiGet<VigilListReply>('/v1/vigils', {
        query: { offset: q.offset, limit: q.limit },
      }),
    get: (name: string) =>
      apiGet<VigilView>(`/v1/vigils/${encodeURIComponent(name)}`),
    create: (body: VigilCreateRequest) =>
      apiSend<VigilView>('/v1/vigils', 'POST', { body }),
    delete: (name: string) =>
      apiSend<void>(`/v1/vigils/${encodeURIComponent(name)}`, 'DELETE'),
  },

  // Oracle: Decree registry (reactor rules). ADR-030.
  decrees: {
    list: (q: ListPagedQuery = {}) =>
      apiGet<DecreeListReply>('/v1/decrees', {
        query: { offset: q.offset, limit: q.limit },
      }),
    get: (name: string) =>
      apiGet<DecreeView>(`/v1/decrees/${encodeURIComponent(name)}`),
    create: (body: DecreeCreateRequest) =>
      apiSend<DecreeView>('/v1/decrees', 'POST', { body }),
    delete: (name: string) =>
      apiSend<void>(`/v1/decrees/${encodeURIComponent(name)}`, 'DELETE'),
  },

  // Multi-target Errand run. Slice W1 (2026-05-27).
  // SSE stream — EventSource on `/v1/errand-runs/:id/events`; fallback to polling if the backend doesn't yet serve SSE.
  errandRuns: {
    create: (body: ErrandRunCreateRequest) =>
      apiSend<ErrandRunCreateReply>('/v1/errand-runs', 'POST', { body }),
    list: (q: ListErrandRunsQuery = {}) =>
      apiGet<ErrandRunListReply>('/v1/errand-runs', {
        query: {
          status: q.status,
          module: q.module,
          offset: q.offset,
          limit: q.limit,
        },
      }),
    get: (errandRunId: string) =>
      apiGet<ErrandRunView>(`/v1/errand-runs/${encodeURIComponent(errandRunId)}`),
    cancel: (errandRunId: string) =>
      apiSend<void>(`/v1/errand-runs/${encodeURIComponent(errandRunId)}`, 'DELETE'),
    // EventSource natively sends the JWT via ?token=... since browser EventSource has no
    // native custom-headers support. Backend SSE route expects Bearer-cookie / query-token;
    // the detail page degrades to polling if EventSource fails.
    events: (errandRunId: string): EventSource =>
      new EventSource(`/v1/errand-runs/${encodeURIComponent(errandRunId)}/events`),
  },

  // Module catalog (commit 530329d). list — for Run->Command module-search;
  // get — detail by full name (params for the auto-form). Read-only.
  // Endpoint is optional for old Keeper deploys — UI graceful-degraded on 404/501.
  modules: {
    list: (q: ListModulesQuery = {}) =>
      apiGet<ModuleCatalogReply>('/v1/modules', {
        query: { errand_safe: q.errand_safe },
      }),
    get: (name: string) =>
      apiGet<ModuleCatalogItem>(`/v1/modules/${encodeURIComponent(name)}`),
    formPrep: (name: string, body: ModuleFormPrepRequest) =>
      apiSend<ModuleFormPrepReply>(`/v1/modules/${encodeURIComponent(name)}/form-prep`, 'POST', { body }),
  },

  // Push-providers registry (ADR-032 amendment 2026-05-26, S7-2). Used in /run Step 2 (Push).
  pushProviders: {
    list: (q: ListPagedQuery = {}) =>
      apiGet<PushProviderListReply>('/v1/push-providers', {
        query: { offset: q.offset, limit: q.limit },
      }),
  },

  // Voyages — unified batch run (ADR-043, S5). Primary endpoint
  // for RunWizard and RunsFeed. kind=scenario -> incarnation.run; kind=command -> errand.run.
  voyages: {
    create: (body: VoyageCreateRequest) =>
      apiSend<VoyageCreateReply>('/v1/voyages', 'POST', { body }),
    preview: (body: VoyageCreateRequest) =>
      apiSend<VoyagePreviewReply>('/v1/voyages/preview', 'POST', { body }),
    list: (q: ListVoyagesQuery = {}) =>
      apiGet<VoyageListReply>('/v1/voyages', {
        query: {
          kind: q.kind,
          status: q.status,
          offset: q.offset,
          limit: q.limit,
        },
      }),
    get: (voyageId: string) =>
      apiGet<Voyage>(`/v1/voyages/${encodeURIComponent(voyageId)}`),
    cancel: (voyageId: string) =>
      apiSend<VoyageCancelReply>(`/v1/voyages/${encodeURIComponent(voyageId)}`, 'DELETE'),
    targets: (voyageId: string) =>
      apiGet<VoyageTargetsReply>(`/v1/voyages/${encodeURIComponent(voyageId)}/targets`),
  },

  // Cadence — recurring scheduled runs (ADR-046).
  cadences: {
    create: (body: CadenceCreateRequest) =>
      apiSend<CadenceCreateReply>('/v1/cadences', 'POST', { body }),
    list: (q: ListCadencesQuery = {}) =>
      apiGet<CadenceListReply>('/v1/cadences', {
        query: {
          enabled: q.enabled,
          kind: q.kind,
          offset: q.offset,
          limit: q.limit,
        },
      }),
    get: (id: string) =>
      apiGet<Cadence>(`/v1/cadences/${encodeURIComponent(id)}`),
    patch: (id: string, body: CadencePatchRequest) =>
      apiSend<Cadence>(`/v1/cadences/${encodeURIComponent(id)}`, 'PATCH', { body }),
    delete: (id: string) =>
      apiSend<void>(`/v1/cadences/${encodeURIComponent(id)}`, 'DELETE'),
    enable: (id: string) =>
      apiSend<CadenceEnabledReply>(`/v1/cadences/${encodeURIComponent(id)}/enable`, 'POST'),
    disable: (id: string) =>
      apiSend<CadenceEnabledReply>(`/v1/cadences/${encodeURIComponent(id)}/disable`, 'POST'),
    runs: (id: string, q: ListPagedQuery = {}) =>
      apiGet<VoyageListReply>(`/v1/cadences/${encodeURIComponent(id)}/runs`, {
        query: { offset: q.offset, limit: q.limit },
      }),
  },

  // Heralds — notification delivery channels (ADR-052, S5).
  heralds: {
    // GET /v1/heralds -> HeraldListReply (sorted updated_at DESC, name ASC).
    list: (q: ListPagedQuery = {}) =>
      apiGet<HeraldListReply>('/v1/heralds', {
        query: { offset: q.offset, limit: q.limit },
      }),
    // GET /v1/heralds/{name} -> Herald.
    get: (name: string) =>
      apiGet<Herald>(`/v1/heralds/${encodeURIComponent(name)}`),
    // POST /v1/heralds -> 201 Herald.
    create: (body: HeraldCreateRequest) =>
      apiSend<Herald>('/v1/heralds', 'POST', { body }),
    // PUT /v1/heralds/{name} -> 200 Herald (replace semantics).
    update: (name: string, body: HeraldUpdateRequest) =>
      apiSend<Herald>(`/v1/heralds/${encodeURIComponent(name)}`, 'PUT', { body }),
    // DELETE /v1/heralds/{name} -> 204. Cascades to delete Tidings.
    delete: (name: string) =>
      apiSend<void>(`/v1/heralds/${encodeURIComponent(name)}`, 'DELETE'),
  },

  // Cloud-Providers — cloud provider registry (ADR-017). Create/list/delete;
  // update is not supported by the contract. credentials — dual-mode (value XOR
  // credentials_ref, ADR-064); the secret is never returned by the server (only credentials_ref).
  providers: {
    // GET /v1/providers -> ProviderListReply.
    list: (q: ListPagedQuery = {}) =>
      apiGet<ProviderListReply>('/v1/providers', {
        query: { offset: q.offset, limit: q.limit },
      }),
    // GET /v1/providers/{name} -> Provider.
    get: (name: string) =>
      apiGet<Provider>(`/v1/providers/${encodeURIComponent(name)}`),
    // POST /v1/providers -> 201 Provider.
    create: (body: ProviderCreateRequest) =>
      apiSend<Provider>('/v1/providers', 'POST', { body }),
    // DELETE /v1/providers/{name} -> 204 (409 if dependent Profiles exist).
    delete: (name: string) =>
      apiSend<void>(`/v1/providers/${encodeURIComponent(name)}`, 'DELETE'),
  },

  // HeraldTypeCatalog — catalog of Herald-channel types (ADR-052 amendment, ADR-042
  // no-hardcode). The list is deterministic and only changes on a
  // Keeper upgrade -> staleTime = Infinity (same pattern as permissions/eventTypes).
  heraldTypes: {
    list: () => apiGet<HeraldTypeCatalogReply>('/v1/herald-types'),
  },

  // EventTypeCatalog — catalog of event-types for the Tiding form (ADR-042, ADR-052).
  // The list is deterministic and only changes on a Keeper upgrade -> staleTime = Infinity.
  eventTypes: {
    list: () => apiGet<EventTypeCatalogReply>('/v1/event-types'),
  },

  // Tidings — notification subscription rules (ADR-052, S5).
  tidings: {
    // GET /v1/tidings -> TidingListReply (sorted updated_at DESC, name ASC).
    list: (q: ListPagedQuery = {}) =>
      apiGet<TidingListReply>('/v1/tidings', {
        query: { offset: q.offset, limit: q.limit },
      }),
    // GET /v1/tidings/{name} -> Tiding.
    get: (name: string) =>
      apiGet<Tiding>(`/v1/tidings/${encodeURIComponent(name)}`),
    // POST /v1/tidings -> 201 Tiding.
    create: (body: TidingCreateRequest) =>
      apiSend<Tiding>('/v1/tidings', 'POST', { body }),
    // PUT /v1/tidings/{name} -> 200 Tiding (replace semantics).
    update: (name: string, body: TidingUpdateRequest) =>
      apiSend<Tiding>(`/v1/tidings/${encodeURIComponent(name)}`, 'PUT', { body }),
    // DELETE /v1/tidings/{name} -> 204.
    delete: (name: string) =>
      apiSend<void>(`/v1/tidings/${encodeURIComponent(name)}`, 'DELETE'),
  },

  // Sigil allow-list for plugins (ADR-026, variant C). Full record path — (namespace, name, ref).
  plugins: {
    sigils: {
      // 200 -> PluginSigilListReply. Only active grants, newest first.
      list: () => apiGet<PluginSigilListReply>('/v1/plugins/sigils'),
      // 201 -> PluginSigilAllowReply. Keeper reads the binary/manifest from the local
      // host cache by (namespace, name); sha256 is computed by Keeper, not the client.
      allow: (body: PluginSigilAllowRequest) =>
        apiSend<PluginSigilAllowReply>('/v1/plugins/sigils', 'POST', { body }),
      // 204 — soft revocation. ref — a single path segment (tag-ref like v1.2.3).
      revoke: (namespace: string, name: string, ref: string) =>
        apiSend<void>(
          `/v1/plugins/sigils/${encodeURIComponent(namespace)}/${encodeURIComponent(name)}/${encodeURIComponent(ref)}`,
          'DELETE',
        ),
    },
  },
};

export interface ListPagedQuery {
  offset?: number;
  limit?: number;
}

// --- helpers for the discriminated union 200/202 on /v1/souls/{sid}/exec ---

function buildAuthHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  };
  const token = tokenStore.get();
  if (token) headers.Authorization = `Bearer ${token}`;
  return headers;
}

function tokenStoreClear(): void {
  tokenStore.clear();
}

export interface ListSoulHistoryQuery {
  // Multi-value `?type=scenario&type=errand` — OR. Empty — both sources.
  type?: SoulHistoryType[];
  // RFC3339; only records with started_at > since.
  since?: string;
  offset?: number;
  limit?: number;
}

export interface ListErrandsQuery {
  sid?: string;
  status?: ErrandStatus;
  started_after?: string;
  // Multi-value `?module=X&module=Y` — exact-match OR (openapi commit 157ee27).
  module?: string[];
  offset?: number;
  limit?: number;
}

export interface ListAuditQuery {
  // Multi-value type/source — exact-match OR.
  type?: string[];
  source?: AuditEventSource[];
  archon_aid?: string;
  correlation_id?: string;
  // Herald channel name from payload (payload->>'herald', exact match).
  payload_herald?: string;
  // voyage_id from payload (payload->>'voyage_id', exact match).
  // For Voyage detail: collects per-incarnation run events of the voyage.
  payload_voyage?: string;
  // RFC3339, both bounds inclusive (see openapi.yaml).
  started_after?: string;
  started_before?: string;
  offset?: number;
  limit?: number;
}

export interface ListOperatorsQuery {
  auth_method?: OperatorAuthMethod;
  // Default server-side = false (only active). true — including revoked.
  revoked?: boolean;
  // Full-text over aid/display_name (typeahead). Local extension until the
  // gen:api regen; after the regen it will match the native q?: string.
  q?: string;
  offset?: number;
  limit?: number;
}

export interface ListPushRunsQuery {
  // Multi-value `?status=` — exact-match OR.
  status?: PushRunStatus[];
  ssh_provider?: string;
  offset?: number;
  limit?: number;
}

export interface ListErrandRunsQuery {
  // Multi-value `?status=` / `?module=` — exact-match OR.
  status?: ErrandRunStatus[];
  module?: string[];
  offset?: number;
  limit?: number;
}

export interface ListModulesQuery {
  // true — only modules with at least one errand-safe state (Run->Command whitelist).
  errand_safe?: boolean;
}

export interface ListCadencesQuery {
  enabled?: boolean;
  kind?: 'scenario' | 'command';
  offset?: number;
  limit?: number;
}
